#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : netkit-telnet
Version  : 0.17
Release  : 2
URL      : https://deb.debian.org/debian/pool/main/n/netkit-telnet/netkit-telnet_0.17.orig.tar.gz
Source0  : https://deb.debian.org/debian/pool/main/n/netkit-telnet/netkit-telnet_0.17.orig.tar.gz
Source1  : https://deb.debian.org/debian/pool/main/n/netkit-telnet/netkit-telnet_0.17-41.2.debian.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-4-Clause
Requires: netkit-telnet-bin = %{version}-%{release}
Requires: netkit-telnet-license = %{version}-%{release}
Requires: netkit-telnet-man = %{version}-%{release}
BuildRequires : ncurses-dev
Patch1: 010-full_set_in_18.patch
Patch2: 020-from_18_to_24.patch
Patch3: 022-buffer_overflow_by_HOME.patch
Patch4: 030-reject_invalid_port.patch
Patch5: 045-avoid_unsetting_term.patch
Patch6: 100-format_security_error.patch
Patch7: 110-markup_errors.patch
Patch8: 120-some_protocol_refinement.patch
Patch9: 124-support_uservar.patch
Patch10: 130-drain_input_from_child.patch
Patch11: 140-telnetlogin_name_check.patch
Patch12: 142-numeric_hosts.patch
Patch13: build.patch
Patch14: CVE-2004-0911.patch
Patch15: CVE-2005_0469.patch

%description
This is netkit-telnet-0.17 for Linux.
This package updates netkit-telnet-0.16.
If you're reading this off a CD, go right away and check the net
archives for later versions and security fixes. As of this writing the
home site for NetKit is
ftp://ftp.uk.linux.org/pub/linux/Networking/netkit

%package bin
Summary: bin components for the netkit-telnet package.
Group: Binaries
Requires: netkit-telnet-license = %{version}-%{release}

%description bin
bin components for the netkit-telnet package.


%package license
Summary: license components for the netkit-telnet package.
Group: Default

%description license
license components for the netkit-telnet package.


%package man
Summary: man components for the netkit-telnet package.
Group: Default

%description man
man components for the netkit-telnet package.


%prep
%setup -q -n netkit-telnet-0.17
cd %{_builddir}
tar xf %{_sourcedir}/netkit-telnet_0.17-41.2.debian.tar.xz
cd %{_builddir}/netkit-telnet-0.17
mkdir -p debian
cp -r %{_builddir}/debian/* %{_builddir}/netkit-telnet-0.17/debian
%patch1 -p1
%patch2 -p1
%patch3 -p1
%patch4 -p1
%patch5 -p1
%patch6 -p1
%patch7 -p1
%patch8 -p1
%patch9 -p1
%patch10 -p1
%patch11 -p1
%patch12 -p1
%patch13 -p1
%patch14 -p1
%patch15 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1579808475
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -fno-lto -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static
make  %{?_smp_mflags}  SUB=telnet

%install
export SOURCE_DATE_EPOCH=1579808475
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/netkit-telnet
cp %{_builddir}/netkit-telnet-0.17/debian/copyright %{buildroot}/usr/share/package-licenses/netkit-telnet/45b5a620e2fd243b83fda098951c3a8879597d5c
%make_install SUB=telnet

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/telnet

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/netkit-telnet/45b5a620e2fd243b83fda098951c3a8879597d5c

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/telnet.1
